snack-exercise/snack-exercise-server

.github/workflows/dev-deploy.yml, appspec.yml
- #8
github actions 에러 log
```
err: docker: Error response from daemon: Conflict. The container name "/spring-dev" is already in use by container "bc3e11fb0441dc1d3a0e0efb06a2b1a4c4d2e2760363253a1f9bbff99b8959e1". You have to remove (or rename) that container to be able to reuse that name.
```
- 이전에 실행하던 컨테이너 중지 및 삭제를 하지 않아서 포트 중복 발생 에러 해결
- dev-deploy.yml에 잘못 적혀있던 컨테이너 이름 수정
=> [CI/CD] dev-deploy.yml 수정

.github/workflows/dev-deploy.yml, appspec.yml, src/main/java/com/soma/snackexercise/SnackExerciseApplication.java, src/main/java/com/soma/snackexercise/domain/BaseTimeEntity.java
- close #23 
- 모든 Entity의 공통 컬럼인 생성시간, 수정시간 컬럼을 위한 BaseTimeEntity를 생성
- JPA Auditing 어노테이션들을 모두 활성화할 수 있도록 Application 클래스에 @EnableJpaAuditing을 추가
=> [Feature] BaseTimeEntity 생성

src/main/java/com/soma/snackexercise/controller/HealthController.java
- #8
- AWS Health Check 성공을 위해서 `/health` uri에 대해서 `health` string을 반환하는 컨트롤러 추가
=> [Feature] AWS Health Check 성공을 위한 컨트롤러 추가

build.gradle, src/main/java/com/soma/snackexercise/controller/HealthController.java
- #8
- AWS Health Check 성공을 위해서 `/health`에 대해서 `health` 문자열이 반환되도록 수정
- HealthController에 @RestController 어노테이션 추가
- build.gradle security관련 의존성 주석 처리
=> [Feature] AWS Health Check 성공을 위한 수정

src/main/java/com/soma/snackexercise/SnackExerciseApplication.java
- 응답을 보내주는 AWS 서버는 https, 응답을 요청하는 swagger 서버는 http를 사용해서 CORS 에러 해결
- Application에 swagger의 url을 변경하는 코드 작성
=> [Fix] swagger cors 에러 해결

src/main/java/com/soma/snackexercise/domain/exercise/Exercise.java
- close #50
- Enum값이 DB에 저장될 때 String 형식으로 저장되도록 수정하였습니다.
=> [Fix]: Enum이 String 데이터 형식으로 저장되도록 수정

src/main/java/com/soma/snackexercise/controller/mission/MissionController.java, src/main/java/com/soma/snackexercise/domain/mission/Mission.java, src/main/java/com/soma/snackexercise/dto/mission/response/MemberMissionDto.java, src/main/java/com/soma/snackexercise/dto/mission/response/TodayMissionCurrentResultDto.java, src/main/java/com/soma/snackexercise/repository/mission/MisssionRepository.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java, src/main/resources/application-local.yml, src/main/resources/data.sql
- close #63
- 당일 릴레이미션 수행 현황 정보 조회 기능을 구현하였습니다.
- 릴레이미션을 할당 받은 시각, 끝낸 시각을 비롯해 해당 미션을 수행한 회원의 정보를 조회할 수 있습니다.
=> [Feature]  당일 릴레이미션 수행 현황 정보 조회 기능

src/main/java/com/soma/snackexercise/repository/mission/MisssionRepository.java
- close #63
- mission과 member가 @ManyToOne(fetch = FetchType.LAZY)로 연관되어있어, mission을 repository에서 조회해올 때, 연관된 member 객체는 프록시 객체 형태로 가져온다. 추후, 실제로 member 객체가 사용될 때 DB에 쿼리를 날려 실제 객체를 가져온다. 이로인해 발생한 N+1 문제를 fetch join으로 해결하였다.
- JOIN -> JOIN FETCH
=> [Refactor] fetch join으로 N+1 문제 해결

src/main/java/com/soma/snackexercise/advice/ErrorCode.java, src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java, src/main/java/com/soma/snackexercise/auth/jwt/filter/JwtAuthenticationProcessingFilter.java, src/main/java/com/soma/snackexercise/auth/jwt/service/JwtService.java, src/main/java/com/soma/snackexercise/auth/oauth/handler/OAuth2LoginSuccessHandler.java, src/main/java/com/soma/snackexercise/controller/auth/AuthController.java, src/main/java/com/soma/snackexercise/controller/signup/SignupController.java, src/main/java/com/soma/snackexercise/dto/auth/AccessTokenResponse.java, src/main/java/com/soma/snackexercise/service/auth/AuthService.java, src/main/java/com/soma/snackexercise/service/signup/SignupService.java, src/main/java/com/soma/snackexercise/util/RedisUtil.java
- close #48 
- 회원가입, 로그인, reissue일 때 refreshToken cookie httponly로 응답 
- accessToken은 http body json으로 응답
- 초기에는 JwtAuthenticationProcessingFilter에서 refreshToken 유무에 따라서 AT을 검증할지, AT/RT을 재발급할지 검증 했었음
- refreshToken은 쿠키에 담기므로 AT만 검증하도록 수정
=> [Refactor] Jwt 인증 인가 로직 리팩토링

src/main/java/com/soma/snackexercise/auth/jwt/filter/JwtAuthenticationProcessingFilter.java, src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java, src/main/java/com/soma/snackexercise/domain/exgroup/Exgroup.java, src/main/java/com/soma/snackexercise/dto/exgroup/response/ExgroupResponse.java, src/main/java/com/soma/snackexercise/service/exgroup/ExgroupService.java, src/main/java/com/soma/snackexercise/service/signup/SignupService.java, src/main/resources/data.sql
- close #79
-  Exgroup 엔티티의 시작 일자, 종료 일자 필드 update 기능 구현
- Exgroup Entity의 시작 일자, 종료 일자, 그룹 목표 일수 필드 추가
- ExgroupResponse에 id, 시작 일자, 종료 일자, 그룹 목표 일수 필드 추가
- controller, service 기능 구현
=> [Feature] 그룹 릴레이 미션 시작 기능 구현

src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java, src/main/java/com/soma/snackexercise/controller/member/MemberController.java, src/main/java/com/soma/snackexercise/controller/mission/MissionController.java, src/main/java/com/soma/snackexercise/dto/exgroup/request/PostCreateExgroupRequest.java, src/main/java/com/soma/snackexercise/dto/exgroup/response/PostCreateExgroupResponse.java, src/main/java/com/soma/snackexercise/dto/member/response/GetOneGroupMemberResponse.java, src/main/java/com/soma/snackexercise/dto/mission/response/MemberMissionDto.java, src/main/java/com/soma/snackexercise/dto/mission/response/RankingResponse.java, src/main/java/com/soma/snackexercise/dto/mission/response/TodayMissionResultResponse.java, src/main/java/com/soma/snackexercise/service/exgroup/ExgroupService.java, src/main/java/com/soma/snackexercise/service/member/MemberService.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- close #76
- 이름, toDto 함수를 사용해 코드 가독성 높임
- Service 클래스의 함수명을 create, read, update, delete로 통일
- Request Dto의 JsonSerialize 삭제
- Swagger 명세서 추가
- 반환시 사용하는 DTO 클래스 명 ResponseDto에서 Response로 수정
- Response Dto에 toDto 메소드 작성하여, Service 클래스에서의 코드 가독성 높임
=> [Chore] Service layer 함수명 통일, Response Dto에 toDto 함수 생성

src/main/java/com/soma/snackexercise/SnackExerciseApplication.java
- 백엔드 서버 도메인 변경에 따라 swagger 도메인을 수정하였습니다.
- 백엔드 서버 도메인을 dev.snackexercise.com에서 dev-api.snackexercise.com으로 수정하였습니다.
=> fix : 백엔드 서버 도메인 변경에 따른 swagger 도메인 수정(#76)

src/main/java/com/soma/snackexercise/domain/joinlist/JoinList.java, src/main/resources/data.sql
- Exgroup, JoinList 엔티티 필드 추가 및 삭제
- Exgroup - missionIntervalTime(미션 수행 간격) 필드 삭제에 따라 더미데이터에서도 해당 컬럼 삭제
- JoinList - executedMissionCount(현재수행완료한 미션 개수) 필드 추가
=> [Fix] Exgroup, JoinList 엔티티 필드 추가 및 삭제

.github/workflows/dev-deploy.yml, docker-compose.yml
- close #94
- docker-compose를 사용하여 redis와 spring boot application 2개의 컨테이너를 관리합니다.
- docker는 각 컨테이너 별로 IP가 생성됩니다. 따라서 spring boot의 yml 파일에서 `spring:data:redis:host : localhost`로 설정시 이는 redis container의 localhost가 아닌 spring boot의 localhost를 의미합니다.
- 이를 위해 docker compose에 spring boot 애플리케이션과 redis 컨테이너를 연결해주는 network를 생성합니다. 
- 네트워크로 연결된 컨테이너들은 컨테이너명으로 해당 컨테이너의 네트워크 접속이 가능합니다. 따라서 `spring:data:redis:host : redis컨테이너명` 으로 수정하여 연결을 성공적으로 수행할 수 있도록 수정하였습니다.
- docker-compose.yml 작성
- dev-deploy.yml docker-compose 버전으로 수정
- application-oauth.yml 파일 수정 (redis의 host)
=> [Feature] docker-compose

src/main/java/com/soma/snackexercise/advice/ErrorCode.java, src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java, src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java, src/test/java/com/soma/snackexercise/controller/exgroup/ExgroupControllerAdviceTest.java, src/test/java/com/soma/snackexercise/controller/exgroup/ExgroupControllerIntegrationTest.java, src/test/java/com/soma/snackexercise/controller/exgroup/ExgroupControllerTest.java, src/test/java/com/soma/snackexercise/factory/dto/ExgroupCreateFactory.java, src/test/java/com/soma/snackexercise/init/TestInitDB.java
- close #93 
- 운동 그룹 ControllerAcvice, 통합 테스트 작성
- ExgroupController API 메소드명 변경 (create, read)
- 에러 핸들러 추가
=> [Test] 운동 그룹 ControllerAcvice, 통합 테스트

.github/workflows/dev-deploy.yml, .gitignore, build.gradle, src/main/java/com/soma/snackexercise/SnackExerciseApplication.java, src/main/java/com/soma/snackexercise/config/ScheduledConfig.java, src/main/java/com/soma/snackexercise/controller/exercise/ExerciseController.java, src/main/java/com/soma/snackexercise/controller/notification/NotificationController.java, src/main/java/com/soma/snackexercise/domain/joinlist/JoinList.java, src/main/java/com/soma/snackexercise/domain/member/Member.java, src/main/java/com/soma/snackexercise/domain/mission/Mission.java, src/main/java/com/soma/snackexercise/domain/notification/NotificationMessage.java, src/main/java/com/soma/snackexercise/dto/member/request/MemberUpdateFcmTokenRequest.java, src/main/java/com/soma/snackexercise/dto/member/response/MemberUpdateFcmTokenResponse.java, src/main/java/com/soma/snackexercise/repository/exgroup/ExgroupRepository.java, src/main/java/com/soma/snackexercise/repository/joinlist/JoinListRepository.java, src/main/java/com/soma/snackexercise/repository/mission/MissionRepository.java, src/main/java/com/soma/snackexercise/service/auth/AuthService.java, src/main/java/com/soma/snackexercise/service/exgroup/ExgroupService.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java, src/main/java/com/soma/snackexercise/service/notification/FirebaseCloudMessageService.java, src/main/java/com/soma/snackexercise/service/notification/NotificationService.java, src/main/resources/application-local.yml, src/main/resources/application.yml, src/main/resources/data.sql
- close #49
- 푸시 알림 기능을 위해 FCM 연동
- 그룹 시작 시간에 미션 할당 기능 추가
- fcmToken 연동 코드 작성
- fcm 알림 전송 요청 서비스 로직 작성
- fcm token 저장 로직 작성
- 로그아웃시 fcmToken 삭제 로직 작성
- 스케줄러를 사용하여 5초 단위로 그룹의 시작시간 여부 검사 및 미션할당 및 알림 기능 추가
=> [Feature] 그룹 시작시간에 미션 할당 기능 구현

src/main/java/com/soma/snackexercise/controller/mission/MissionController.java, src/main/java/com/soma/snackexercise/domain/group/Group.java, src/main/java/com/soma/snackexercise/domain/joinlist/JoinList.java, src/main/java/com/soma/snackexercise/domain/mission/Mission.java, src/main/java/com/soma/snackexercise/domain/notification/NotificationMessage.java, src/main/java/com/soma/snackexercise/dto/mission/request/MissionFinishRequest.java, src/main/java/com/soma/snackexercise/dto/mission/response/MissionFinishResponse.java, src/main/java/com/soma/snackexercise/exception/FcmTokenEmptyException.java, src/main/java/com/soma/snackexercise/repository/joinlist/JoinListRepository.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java, src/main/java/com/soma/snackexercise/service/mission/MissionUtil.java, src/main/resources/data.sql, src/test/java/com/soma/snackexercise/factory/entity/MissionFactory.java, src/test/java/com/soma/snackexercise/repository/joinlist/JoinListRepositoryTest.java
- close #112
- 운동 미션 수행 완료 API 작성
- Exgroup 엔티티에 그룹 목표 달성 여부 컬럼을 추가하였습니다.
- 운동 종료시, 시간 기록 로직을 종료한 현재 시각을 기록하는 기존 방식에서, 시작시간 + 영상의 길이를 종료시간으로 기록하도록 수정하였습니다.
- MissionService, MissionSchedulerService에서 공통으로 사용하는 함수는 MissionUtil 클래스로 분리하였습니다.
- 미션 수행 완료 API를 작성하였습니다.
=> [Feature] 운동 미션 수행 완료 API

src/main/java/com/soma/snackexercise/SnackExerciseApplication.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java
- 스프링부트 애플리케이션 TimeZone 설정
- 스케줄러 주기 조정
- 스프링부트 애플리케이션 TimeZone 설정
- 스프링부트는 실행되는 서버 환경의 TimeZone을 따라간다. 현재 docker exec spring-dev date로 확인해보니 docker의 기본 시간대가 UTC로 설정되어있었다. 따라서 @PostConstruct로 timezone을 설정했다. 
- 그러나 타임존 설정을 위한 코드가 프로덕션 코드에 포함되기에, 추후에 docker compose에 environment를 사용하여 timezone을 설정하도록 수정하는 것을 고려해볼 수 있다.
- 스케줄러 주기 조정
- 그룹 시작 시간에 미션 할당 스케줄링 기능과, 미션 할당 시각 기준으로 일정 시각 이내에 미션을 수행하지 않을 경우 알람을 보내주는 스케줄링 기능의 경우, 최소 설정 시간 단위가 분이므로 1분 마다 스케줄러가 실행되도록 하였다.
- 그룹의 종료일자가 지났을 경우 Group, JoinList의 Status를 Inactive로 수정하는 작업은 1분마다 실행할 정도로 중요한 작업은 아니라고 생각하여 1시간 마다 실행되도록 주기를 수정하였다.
=> [Fix]  스프링부트 애플리케이션 TimeZone 설정, 스케줄러 주기 조정

src/main/java/com/soma/snackexercise/advice/ErrorCode.java, src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java, src/main/java/com/soma/snackexercise/controller/exercise/ExerciseController.java, src/main/java/com/soma/snackexercise/controller/member/MemberController.java, src/main/java/com/soma/snackexercise/domain/group/CreateGroupCode.java, src/main/java/com/soma/snackexercise/domain/mission/Mission.java, src/main/java/com/soma/snackexercise/dto/group/response/GroupResponse.java, src/main/java/com/soma/snackexercise/exception/NotStartedGroupException.java, src/main/java/com/soma/snackexercise/service/group/GroupService.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- API 검토 및 수정
- 그룹 코드 영어 + 숫자 조합에서 숫자 조합으로 변경
- 에러 핸들러 추가 : 존재하지 않는 운동, 그룹 시작 안했을 경우 에러 핸들러 추가
- 스케줄러 시간 단위 1분으로 조정함에 따라서 로직 수정
- 그룹 시작 시간에 미션 할당 시, 현재 시각을 기준으로 앞 1분, 뒤 1분 모두 미션이 할당되게 되는 문제를 현재 시각이 그룹 시작 시간보다 이후인 경우에만 할당이 되도록 로직 수정
=> [Fix] 스케줄러 시간 단위 수정

src/main/java/com/soma/snackexercise/dto/group/response/GroupResponse.java
- 하나의 그룹 정보 조회 API의 response에 그룹 코드 필드 추가
보안 상의 이유로 클라이언트 측에 그룹코드를 넘기지 않아야겠다고 생각하여 삭제했으나, 클라이언트에서 그룹 초대시 초대 코드를 사용해야함에 따라서 추가하였다.
- 하나의 그룹 정보 조회 API의 response에 그룹 코드 필드 추가
=> [Fix] 그룹코드 필드 추가

src/main/java/com/soma/snackexercise/repository/group/GroupRepository.java, src/main/java/com/soma/snackexercise/service/group/GroupService.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java, src/main/java/com/soma/snackexercise/service/mission/MissionUtil.java
- 그룹 시작 시 미션 할당 API 현재 수행 중인 멤버 update 로직 추가
- 그룹 시작 시간 미션 할당 스케줄러 수정
- 그룹 시작 시 미션 할당 API에서, 미션을 할당 해주지만, group 테이블의 currentDoingMemberId 필드는 update가 되지 않는다는 에러를 해결
- currentDoingMemberId 컬럼은 역정규화 필드로 우리가 직접 신경써서 update를 해줘야한다.
- 그룹 시작 시간에 미션 할당 스케줄러에서, 아직 시작하지 않은 그룹은 제외하도록 수정
=> [Fix] 그룹 시작 시 미션 할당 API 현재 수행 중인 멤버 update 로직 추가

src/main/java/com/soma/snackexercise/SnackExerciseApplication.java, src/main/java/com/soma/snackexercise/domain/notification/NotificationMessage.java, src/main/java/com/soma/snackexercise/repository/group/GroupRepository.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java, src/main/java/com/soma/snackexercise/service/notification/FirebaseCloudMessageService.java
- 스케줄러 비동기 처리
- 자동 독촉 스케줄러에서 미션 수행자와 나머지 그룹원 푸시 알림 분리
- 스케줄러 비동기 처리
- 각각의 스케줄러가 개별적으로 동작되어야 하기에 비동기 처리를 수행하는 코드를 추가하였습니다.
- 각 함수에 @Async, Application Class에는 @EnableAsync 어노테이션을 추가하였습니다.
- 자동 독촉 스케줄러에서 미션 수행자와 나머지 그룹원 푸시 알림 분리
- 미션 수행자에게는 미션 수행을 독려하는 푸시 메세지 전송
- 미션 수행자 이외의 그룹원에게는 미션 수행자의 미션 수행을 독촉하라는 푸시 메시지 전송
- 그룹 시작 시간 미션 할당 스케줄러에서 그룹 생성 일자가 아닌, 그룹 시작 일자가 null이 아닌 그룹 가져오기로 repository 수정
- 그룹이 시작하면 그룹 시작 일자가 null이 아닌 실제 날짜값이 기록됩니다. 따라서, 그룹이 DB에 생성될 때 기록되는 그룹 생성일자가 아닌, 그룹 시작 일자의 null 여부를 체크해야합니다.
=> [Fix] 스케줄러 비동기 처리, 자동 독촉 스케줄러에서 미션 수행자와 나머지 그룹원 푸시 알림 분리

src/main/java/com/soma/snackexercise/dto/auth/MvpLoginRequest.java, src/main/java/com/soma/snackexercise/dto/signup/SignupRequest.java, src/main/java/com/soma/snackexercise/service/auth/MvpAuthService.java, src/main/java/com/soma/snackexercise/service/signup/SignupService.java
- 로그인, 회원가입시 fcmToken 받도록 수정
- 기존에 FcmToken 저장 API는 추후 OAuth 로그인시 필요하기에 남겨두기로 결정
- mvp 로그인, 회원가입의 request body에 fcmToken 추가로 받도록 설정
=> [Fix] 로그인, 회원가입시 fcmToken 받도록 수정

src/main/java/com/soma/snackexercise/controller/group/GroupController.java, src/main/java/com/soma/snackexercise/domain/group/Group.java, src/main/java/com/soma/snackexercise/domain/joinlist/JoinList.java, src/main/java/com/soma/snackexercise/dto/group/response/FinishedGroupResponse.java, src/main/java/com/soma/snackexercise/repository/joinlist/JoinListRepository.java, src/main/java/com/soma/snackexercise/repository/mission/MissionRepository.java, src/main/java/com/soma/snackexercise/service/group/GroupService.java
- 당일 미션 랭킹 조회 API 수정
- 종료된 그룹 정보 조회하기 API 구현
- 그룹 코드로 그룹 가입 API에서 이미 시작한 그룹에 중간에 참여하는 참여자에 대한 로직 추가
- 당일 미션 랭킹 조회 API 수정
- 미션을 시작하고, 수행하는 중인데도 불구하고 상대방의 화면에서는 미션 랭킹에 보여지는 에러 처리
- 종료된 미션에 대해서만 랭킹에서 보여지도록 로직 수정
- 종료된 그룹 정보 조회하기 API 구현
- 그룹 코드로 그룹 가입 API에서 이미 시작한 그룹에 중간에 참여하는 참여자에 대한 로직 추가
- 가장 적은 미션 수행횟수를 가진 사람들 중에서 랜덤하게 미션이 부여되기에, 중간 참여자의 경우, 그룹원들 중 가장 적은 수행횟수만큼 수행했다고 간주하는 로직을 추가해야한다.
=> [Fix] 당일 미션 랭킹 조회, 그룹코드로 그룹 가입 API 수정 및 종료된 그룹 정보 조회 API 구현

src/main/java/com/soma/snackexercise/dto/group/response/FinishedGroupResponse.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- 종료된 그룹 정보 조회 API response 수정
- 미션 수행 완료 API 로그 회원명 추가
- 종료된 그룹 정보 조회 response 그룹 목표 성공 여부 필드 추가
- 미션 수행완료 API에서 미션 수행 완료시 회원명 로그 출력
=> [Fix] 종료된 그룹 정보 조회 response 그룹 목표 성공 여부 필드 추가

src/main/java/com/soma/snackexercise/domain/group/Group.java, src/main/java/com/soma/snackexercise/dto/group/response/GroupResponseIncludeHost.java, src/main/java/com/soma/snackexercise/repository/joinlist/JoinListRepository.java, src/main/java/com/soma/snackexercise/service/group/GroupService.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- 그룹 목표 성공시 즉시 그룹, JoinList INACTIVE 처리
- 그룹 1개 정보 조회시 HOST 회원 ID도 전달하도록 수정
- 내용을 적어주세요.
=> [Fix] 그룹 목표 성공시 즉시 그룹, JoinList INACTIVE 처리

build.gradle, src/main/java/com/soma/snackexercise/advice/ErrorCode.java, src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java, src/main/java/com/soma/snackexercise/controller/auth/MvpAuthController.java, src/main/java/com/soma/snackexercise/domain/notification/NotificationMessage.java, src/main/java/com/soma/snackexercise/dto/auth/MvpLoginRequest.java, src/main/java/com/soma/snackexercise/service/group/GroupService.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- fcm 토큰이 빈값이어서 500에러 발생을 방지하기 위해서, 로그인 및 회원가입시 NULL, "", " "을 허용하지 않는 NOT BLANK validation을 추가하였습니다. 
- 푸시 알림 메세지에 그룹의 이름을 추가하였습니다.
- 내용을 적어주세요.
=> [Fix] FCM 토큰 빈 값, null validation 추가

src/main/java/com/soma/snackexercise/domain/notification/NotificationMessage.java, src/main/java/com/soma/snackexercise/service/group/GroupService.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java
- 자동 독촉 푸시 알림 전송시 그룹명과 현재 미션 중인 회원명 나오도록 수정
- 그룹 시작후 바로 미션 할당 푸시 알림 전송 로직 추가
- 내용을 적어주세요.
=> [Fix] 그룹 시작후 바로 미션 할당 푸시 알림 전송 로직 추가

src/main/java/com/soma/snackexercise/advice/ErrorCode.java, src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java, src/main/java/com/soma/snackexercise/exception/group/DuplicateGroupNameException.java, src/main/java/com/soma/snackexercise/repository/group/GroupRepository.java, src/main/java/com/soma/snackexercise/service/group/GroupService.java
- close #182
- 방장이면서 현재 진행중인 그룹들의 이름과 새로 가입하려는 그룹명이 같은 것이 하나 이상 존재하는지 여부 판단하는 repository 함수 생성
- 방장이면서 현재 진행중인 그룹들의 이름과 새로 가입하려는 그룹명이 같은 것이 하나 이상 존재하면 DUPLICATE_GROUP_EXCEPTION을 반환하는 service 함수의 로직 처리
- 내용을 적어주세요.
=> [Fix] 현재 본인이 방장이면서 진행중인 그룹명과 중복인 그룹 생성 불가능 로직 추가 

src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- close #189
- 당일에 수행한 릴레이 횟수가 아니라, 그룹의 기간동안 수행한 릴레이횟수를 반환
- 내용을 적어주세요.
=> [Fix] 그룹의 기간동안 수행한 릴레이횟수를 반환
