feature3, test.txt
- close #3 
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Feature] 이슈테스트

.github/workflows/prod-deploy.yml
- #8 
[Error: .github#L1](https://github.com/snack-exercise/snack-exercise-server/pull/12/files#annotation_12501595372)
every step must define a `uses` or `run` key
에러 해결
- uses, run 앞의 `-` 삭제
=> [CI/CD] prod 테스트

src/main/java/com/soma/snackexercise/advice/ErrorCode.java, src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java, src/main/java/com/soma/snackexercise/util/response/Failure.java, src/main/java/com/soma/snackexercise/util/response/Response.java, src/main/java/com/soma/snackexercise/util/response/Result.java, src/main/java/com/soma/snackexercise/util/response/Success.java
=> [Feature] 코드 아키텍처 및 패키지 구조화

.github/workflows/dev-deploy.yml, .github/workflows/prod-deploy.yml
- #8 
- dev-deploy.yml CI/CD 테스트
=> [CI/CD] dev-deploy.yml 테스트

appspec.yml
- #8
- code deploy 에러 해결을 위해 appspec.yml을 수정하였습니다.
- permissions, files부분을 작성하였습니다.
=> [CI/CD] appspec.yml 수정

.gitignore, build.gradle, src/main/java/com/soma/snackexercise/domain/member/Member.java, src/main/java/com/soma/snackexercise/domain/member/Role.java, src/main/java/com/soma/snackexercise/domain/member/SocialType.java, src/main/java/com/soma/snackexercise/repository/member/MemberRepository.java, src/main/java/com/soma/snackexercise/util/constant/Gender.java, src/main/java/com/soma/snackexercise/util/constant/Status.java, src/main/resources/application-local.yml
- close #18 
- build 관련 설정 및 Member 엔티티 추가
=> [Feature] build 관련 설정 및 Member 엔티티 추가

.gitignore, build.gradle, src/main/java/com/soma/snackexercise/SnackExerciseApplication.java, src/main/java/com/soma/snackexercise/controller/HealthController.java, src/main/java/com/soma/snackexercise/domain/BaseTimeEntity.java, src/main/java/com/soma/snackexercise/domain/member/Member.java, src/main/java/com/soma/snackexercise/domain/member/Role.java, src/main/java/com/soma/snackexercise/domain/member/SocialType.java, src/main/java/com/soma/snackexercise/repository/member/MemberRepository.java, src/main/java/com/soma/snackexercise/util/constant/Gender.java, src/main/java/com/soma/snackexercise/util/constant/Status.java, src/main/resources/application-local.yml
=> [Feature] OAuth 로그인 기본 설정

.github/workflows/dev-deploy.yml, .gitignore, build.gradle, src/main/resources/application.yml
- #30 
- application-jwt.yml, application-oauth.yml 파일 추가
- docker run할 때 특정 profile 지정
=> [Fix] dev-deploy 배포 파일 수정

src/main/resources/application-local.yml
- close #30 
- redis 설정 application-local.yml에서 application-oauth.yml로 이동
=> [Fix] dev-deploy 배포 파이프라인 수정

build.gradle
- close #36 
- 테스트 커버리지 측정을 위한 Jacoco 의존성 추가
=> [Feature] Jacoco 의존성 추가

src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java, src/main/java/com/soma/snackexercise/domain/exgroup/CreateExgroupCode.java, src/main/java/com/soma/snackexercise/domain/exgroup/Exgroup.java, src/main/java/com/soma/snackexercise/domain/joinlist/JoinList.java, src/main/java/com/soma/snackexercise/domain/joinlist/JoinType.java, src/main/java/com/soma/snackexercise/dto/exgroup/PostCreateExgroupRequest.java, src/main/java/com/soma/snackexercise/dto/exgroup/PostCreateExgroupResponse.java, src/main/java/com/soma/snackexercise/repository/exgroup/ExgroupRepository.java, src/main/java/com/soma/snackexercise/repository/joinlist/JoinListRepository.java, src/main/java/com/soma/snackexercise/service/exgroup/ExgroupService.java, src/main/java/com/soma/snackexercise/util/response/Failure.java, src/main/java/com/soma/snackexercise/util/response/Success.java
=> [Feature] 운동 그룹 생성 구현

src/main/java/com/soma/snackexercise/advice/ErrorCode.java, src/main/java/com/soma/snackexercise/util/response/Response.java
- close #43 
- ErrorCode Enum에서 code, message 관리하도록 수정
- ErrorCode Enum 에러코드, 에러메세지 필드 생성
- Response failure 함수 매개변수 수정
=> [Refactor] ErrorCode Enum에서 code, message 관리 

src/main/java/com/soma/snackexercise/exception/ExgroupNotFoundException.java
- close #33
- 운동 그룹 조회 실패 에러 클래스가 존재하지 않아 dev-deploy action 실패
- 운동 그룹 조회 실패 에러 클래스 생성
=> [Fix] 운동 그룹 조회 실패 에러 클래스 생성

src/main/java/com/soma/snackexercise/advice/ErrorCode.java, src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java, src/main/java/com/soma/snackexercise/auth/jwt/filter/JwtAuthenticationProcessingFilter.java, src/main/java/com/soma/snackexercise/auth/jwt/handler/JwtAccessDeniedHandler.java, src/main/java/com/soma/snackexercise/auth/jwt/service/JwtService.java, src/main/java/com/soma/snackexercise/config/SecurityConfig.java, src/main/java/com/soma/snackexercise/controller/auth/AuthController.java, src/main/java/com/soma/snackexercise/controller/signup/SignupController.java, src/main/java/com/soma/snackexercise/domain/member/Member.java, src/main/java/com/soma/snackexercise/dto/signup/SignupRequest.java, src/main/java/com/soma/snackexercise/exception/ExpiredJwtException.java, src/main/java/com/soma/snackexercise/exception/InvalidRefreshTokenException.java, src/main/java/com/soma/snackexercise/exception/MemberNameAlreadyExistsException.java, src/main/java/com/soma/snackexercise/exception/UnauthorizedException.java, src/main/java/com/soma/snackexercise/repository/member/MemberRepository.java, src/main/java/com/soma/snackexercise/service/auth/AuthService.java, src/main/java/com/soma/snackexercise/service/signup/SignupService.java, src/main/java/com/soma/snackexercise/util/RedisUtil.java
- close #38 
- 추가 회원가입 API 작성
- jwt 검증 로직 추가 및 수정
- 로그아웃시 블랙리스트된 jwt 토큰 검증 기능 추가
=> [Feature] 추가 회원가입 및 검증 로직 추가

src/main/java/com/soma/snackexercise/domain/BaseEntity.java, src/main/java/com/soma/snackexercise/domain/exgroup/Exgroup.java, src/main/java/com/soma/snackexercise/domain/joinlist/JoinList.java, src/main/java/com/soma/snackexercise/domain/member/Member.java
- close #51
모든 Entity에 삭제 여부를 담고 있는 status 필드가 있다.
또한, 해당 필드를 삭제시 INACTIVE로 변경해주기 위한 inActive()함수도 모든 엔티티에 공통적으로 작성해줘야한다.
해당 반복 작업을 모든 엔티티가 필요로하는 status 컬럼과 inActive()함수를 포함하며, BaseTimeEntity를 상속받아 생성일시, 수정일시가 포함된 BaseTimeEntity를 생성한다.
=> [Refactor] BaseEntity를 사용한 리팩토링

build.gradle, src/main/java/com/soma/snackexercise/config/SecurityConfig.java, src/main/java/com/soma/snackexercise/config/SwaggerConfig.java, src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java
- close #53
- API 문서화를 위해 Swagger를 적용하였습니다.
=> [Feature] Swagger 적용

src/main/java/com/soma/snackexercise/config/WebConfig.java
- close #60
- 필터, Config, @CrossOrigin 어노테이션을 사용해 특정 컨트롤러 혹은 특정 메서에 대해서 CORS를 적용할 수 있습니다. 
- 그 중에서 Config를 사용해 전역적으로 CORS 에러를 처리하였습니다.
- WebConfig 작성
=> fix : CORS 에러 해결

src/main/java/com/soma/snackexercise/domain/exercise/Exercise.java, src/main/java/com/soma/snackexercise/domain/exercise/ExerciseCategory.java, src/main/java/com/soma/snackexercise/repository/exercise/ExerciseRepository.java
- close #50
- Exercise Entity, Repository 클래스 생성
=> [Feature] Exercise Entity, Repository 클래스 생성

src/main/java/com/soma/snackexercise/advice/ErrorCode.java, src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java, src/main/java/com/soma/snackexercise/controller/mission/MissionController.java, src/main/java/com/soma/snackexercise/dto/mission/response/RankingResponseDto.java, src/main/java/com/soma/snackexercise/exception/WrongRequestParamException.java, src/main/java/com/soma/snackexercise/repository/mission/MisssionRepository.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- close #68
- 당일 랭킹 기능
- 누적 랭킹 기능
- 다만, jpql에서 TIMESTAMPDIFF 함수가 기본 제공되지 않아, 빠른 구현을 위해서 우선 자바코드로 수행하였습니다.
=> [Feature] 랭킹 기능 구현 

src/main/java/com/soma/snackexercise/controller/mission/MissionController.java
- close #68
- swagger에 Query Param에 대한 설명을 추가하는 코드를 작성하였습니다.
=> [Chore] swagger에 Query Param 설명 추가

src/main/java/com/soma/snackexercise/controller/exercise/ExerciseController.java, src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java, src/main/java/com/soma/snackexercise/controller/member/MemberController.java, src/main/java/com/soma/snackexercise/domain/exercise/Exercise.java, src/main/java/com/soma/snackexercise/domain/exgroup/Exgroup.java, src/main/java/com/soma/snackexercise/domain/member/Member.java, src/main/java/com/soma/snackexercise/dto/exercise/request/ExerciseCreateRequest.java, src/main/java/com/soma/snackexercise/dto/exercise/request/ExerciseUpdateRequest.java, src/main/java/com/soma/snackexercise/dto/exercise/response/ExerciseResponse.java, src/main/java/com/soma/snackexercise/dto/exgroup/request/ExgroupUpdateRequest.java, src/main/java/com/soma/snackexercise/dto/exgroup/request/PostCreateExgroupRequest.java, src/main/java/com/soma/snackexercise/dto/exgroup/response/ExgroupResponse.java, src/main/java/com/soma/snackexercise/dto/member/request/MemberUpdateRequest.java, src/main/java/com/soma/snackexercise/dto/member/response/MemberResponse.java, src/main/java/com/soma/snackexercise/exception/ExerciseNotFoundException.java, src/main/java/com/soma/snackexercise/exception/MaxMemberNumLessThanCurrentException.java, src/main/java/com/soma/snackexercise/exception/NotHostException.java, src/main/java/com/soma/snackexercise/repository/exgroup/ExgroupRepository.java, src/main/java/com/soma/snackexercise/repository/joinlist/JoinListRepository.java, src/main/java/com/soma/snackexercise/repository/member/MemberRepository.java, src/main/java/com/soma/snackexercise/service/exercise/ExerciseService.java, src/main/java/com/soma/snackexercise/service/exgroup/ExgroupService.java, src/main/java/com/soma/snackexercise/service/member/MemberService.java
- close #70 
회원 수정, 그룹 수정, 운동 CRUD 작성
회원, 그룹, 운동 수정 메소드를 PUT으로 변경
=> [Feature] 회원, 그룹, 운동 수정 삭제 API

src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java, src/main/java/com/soma/snackexercise/domain/joinlist/JoinList.java, src/main/java/com/soma/snackexercise/exception/JoinListNotFoundException.java, src/main/java/com/soma/snackexercise/exception/NotExgroupHostException.java, src/main/java/com/soma/snackexercise/exception/NotExgroupMemberException.java, src/main/java/com/soma/snackexercise/exception/NotHostException.java, src/main/java/com/soma/snackexercise/repository/joinlist/JoinListRepository.java, src/main/java/com/soma/snackexercise/repository/mission/MissionRepository.java, src/main/java/com/soma/snackexercise/service/exgroup/ExgroupService.java, src/main/java/com/soma/snackexercise/service/member/MemberDeletionService.java, src/main/java/com/soma/snackexercise/service/member/MemberService.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- close #78 
방장이 그룹에서 회원 탈퇴 API
회원이 그룹 탈퇴 API
=> [Feature] 방장이 회원 강퇴 / 회원이 탈퇴 API

build.gradle, src/main/java/com/soma/snackexercise/auth/oauth/service/CustomOAuth2UserService.java, src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java, src/main/java/com/soma/snackexercise/domain/exgroup/Exgroup.java, src/main/java/com/soma/snackexercise/dto/exgroup/request/ExgroupCreateRequest.java, src/main/java/com/soma/snackexercise/dto/exgroup/request/ExgroupUpdateRequest.java, src/main/java/com/soma/snackexercise/dto/exgroup/response/ExgroupCreateResponse.java, src/main/java/com/soma/snackexercise/dto/exgroup/response/ExgroupResponse.java, src/main/java/com/soma/snackexercise/repository/joinlist/JoinListRepository.java, src/main/java/com/soma/snackexercise/repository/member/MemberRepository.java, src/main/java/com/soma/snackexercise/repository/mission/MissionRepository.java, src/main/java/com/soma/snackexercise/service/exgroup/ExgroupService.java, src/test/java/com/soma/snackexercise/factory/dto/ExgroupCreateFactory.java, src/test/java/com/soma/snackexercise/factory/dto/ExgroupUpdateFactory.java, src/test/java/com/soma/snackexercise/factory/entity/ExerciseFactory.java, src/test/java/com/soma/snackexercise/factory/entity/ExgroupFactory.java, src/test/java/com/soma/snackexercise/factory/entity/JoinListFactory.java, src/test/java/com/soma/snackexercise/factory/entity/MemberFactory.java, src/test/java/com/soma/snackexercise/factory/entity/MissionFactory.java, src/test/java/com/soma/snackexercise/repository/exgroup/ExgroupRepositoryTest.java, src/test/java/com/soma/snackexercise/repository/joinlist/JoinListRepositoryTest.java, src/test/java/com/soma/snackexercise/repository/member/MemberRepositoryTest.java, src/test/java/com/soma/snackexercise/repository/mission/MissionRepositoryTest.java, src/test/java/com/soma/snackexercise/service/exgroup/ExgroupServiceTest.java
- close #84 
- Member, JoinList, Exgroup, Mission Repository 계층 단위 테스트 작성
- Exgroup Service 계층 테스트 코드 작성
- Repository @Param import 수정
- Repository 메소드 조건 (Status 필드) 추가
- Jacoco 주석 처리
- 운동 생성 DTO 이름 수정
- 그룹 생성, 수정 DTO 필드 수정
=> [Test] Repository, Service 계층 단위 테스트 코드 작성

src/main/java/com/soma/snackexercise/config/WebConfig.java
- GET 요청을 제외한 POST 요청에서는 CORS에러 발생하는 문제 해결
- WebConfig의 
`allowedMethods("*")`를 
`allowedMethods("POST", "GET", "PUT", "DELETE", "OPTIONS")`로 수정
=> [Fix] CORS 에러 해결

build.gradle, src/main/java/com/soma/snackexercise/auth/oauth/handler/OAuth2LoginFailureHandler.java, src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java, src/main/java/com/soma/snackexercise/dto/exgroup/request/ExgroupCreateRequest.java, src/main/java/com/soma/snackexercise/dto/exgroup/request/ExgroupUpdateRequest.java, src/main/java/com/soma/snackexercise/dto/exgroup/response/ExgroupResponse.java, src/test/java/com/soma/snackexercise/config/TestUserArgumentResolver.java, src/test/java/com/soma/snackexercise/controller/exgroup/ExgroupControllerTest.java, src/test/java/com/soma/snackexercise/factory/dto/ExgroupReadFactory.java
- close #86 
- 운동그룹 Controller 계층 단위 테스트 작성
- Request Response DTO 날짜 타입 필드 직렬화 어노테이션 추가
=> [Test] 운동그룹 Controller 계층 단위 테스트 작성

src/main/java/com/soma/snackexercise/auth/oauth/OAuthAttributes.java, src/main/java/com/soma/snackexercise/domain/member/Member.java, src/main/java/com/soma/snackexercise/domain/mission/Mission.java, src/main/java/com/soma/snackexercise/dto/member/request/MemberUpdateRequest.java, src/main/java/com/soma/snackexercise/dto/mission/response/RankingResponse.java, src/main/java/com/soma/snackexercise/dto/signup/SignupRequest.java, src/main/java/com/soma/snackexercise/exception/CalculateMinutesDiffException.java, src/main/java/com/soma/snackexercise/repository/exgroup/ExgroupRepository.java, src/main/java/com/soma/snackexercise/repository/member/MemberRepository.java, src/main/java/com/soma/snackexercise/repository/mission/MissionRepository.java, src/main/java/com/soma/snackexercise/service/exgroup/ExgroupService.java, src/main/java/com/soma/snackexercise/service/member/MemberService.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java, src/main/java/com/soma/snackexercise/service/signup/SignupService.java, src/test/java/com/soma/snackexercise/controller/exgroup/ExgroupControllerAdviceTest.java, src/test/java/com/soma/snackexercise/controller/exgroup/ExgroupControllerTest.java, src/test/java/com/soma/snackexercise/factory/entity/MemberFactory.java, src/test/java/com/soma/snackexercise/factory/entity/MissionFactory.java, src/test/java/com/soma/snackexercise/repository/exgroup/ExgroupRepositoryTest.java, src/test/java/com/soma/snackexercise/repository/member/MemberRepositoryTest.java, src/test/java/com/soma/snackexercise/repository/mission/MissionRepositoryTest.java, src/test/java/com/soma/snackexercise/service/exgroup/ExgroupServiceTest.java, src/test/java/com/soma/snackexercise/service/mission/MissionServiceTest.java, src/test/java/com/soma/snackexercise/utils/ReflectionTestUtils.java, src/test/java/com/soma/snackexercise/utils/TestUserArgumentResolver.java
- close #98 
- 미션 서비스 클래스 리팩토링
- 추가 회원가입 시 nickname 필드 받도록 변경
- 미션 Service 계층 테스트 코드 작성
- 미션 Service 및 Repository Javadoc 작성
=> [Test] 미션 Service 계층 테스트 코드 및 Javadoc 작성

src/main/java/com/soma/snackexercise/repository/mission/MissionRepository.java, src/test/java/com/soma/snackexercise/factory/entity/MemberFactory.java, src/test/java/com/soma/snackexercise/repository/member/MemberRepositoryTest.java, src/test/java/com/soma/snackexercise/service/exgroup/ExgroupServiceTest.java, src/test/java/com/soma/snackexercise/service/mission/MissionServiceTest.java
=> fix : 테스트 코드 오류 수정 (#98)

src/main/java/com/soma/snackexercise/controller/group/GroupController.java, src/main/java/com/soma/snackexercise/domain/joinlist/JoinList.java, src/main/java/com/soma/snackexercise/dto/group/response/JoinGroupResponse.java, src/main/java/com/soma/snackexercise/repository/joinlist/JoinListRepository.java, src/main/java/com/soma/snackexercise/service/group/GroupService.java, src/main/resources/data.sql
- close #107
- 회원이 가입하고 있는 모든 그룹 조회 API
- 필드명 exgroupId에서 exgroup으로 수정
- 회원이 현재 가입하고 있고, 종료되지 않고 활성화되어있는 모든 그룹 조회
=> [Feat] 회원이 가입하고 있는 모든 그룹 조회 API

src/main/java/com/soma/snackexercise/advice/ErrorCode.java, src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java, src/main/java/com/soma/snackexercise/auth/jwt/filter/JwtAuthenticationProcessingFilter.java, src/main/java/com/soma/snackexercise/config/SecurityConfig.java, src/main/java/com/soma/snackexercise/config/WebConfig.java, src/main/java/com/soma/snackexercise/controller/auth/MvpAuthController.java, src/main/java/com/soma/snackexercise/dto/auth/MvpLoginRequest.java, src/main/java/com/soma/snackexercise/dto/auth/MvpLoginResponse.java, src/main/java/com/soma/snackexercise/exception/MemberNicknameAlreadyExistsException.java, src/main/java/com/soma/snackexercise/service/auth/MvpAuthService.java
=> fix : 1차 MVP 배포 임시 로그인 방식 변경 (#111)

src/main/java/com/soma/snackexercise/service/auth/MvpAuthService.java
=> fix : AccessToken 스트링 변경 (#111)

src/main/java/com/soma/snackexercise/auth/jwt/service/JwtService.java, src/main/java/com/soma/snackexercise/service/auth/MvpAuthService.java
=> fix : Authenticaion 역할 임시 지정 (#111)

src/main/java/com/soma/snackexercise/config/SecurityConfig.java, src/main/java/com/soma/snackexercise/controller/auth/MvpAuthController.java, src/main/java/com/soma/snackexercise/repository/member/MemberRepository.java, src/main/java/com/soma/snackexercise/service/auth/MvpAuthService.java
=> feat : MVP용 임시 회원 가입 로직 추가 (#111)

src/main/java/com/soma/snackexercise/controller/mission/MissionController.java, src/main/java/com/soma/snackexercise/dto/mission/response/MissionResponse.java, src/main/java/com/soma/snackexercise/exception/MissionNotFoundException.java, src/main/java/com/soma/snackexercise/repository/joinlist/JoinListRepository.java, src/main/java/com/soma/snackexercise/repository/mission/MissionRepository.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java, src/test/java/com/soma/snackexercise/repository/joinlist/JoinListRepositoryTest.java
=> feat : 미션 정보 받기 API 추가 (#116)

src/main/java/com/soma/snackexercise/advice/ErrorCode.java, src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java, src/main/java/com/soma/snackexercise/controller/mission/MissionController.java, src/main/java/com/soma/snackexercise/dto/mission/request/MissionStartRequest.java, src/main/java/com/soma/snackexercise/dto/mission/response/MissionResponse.java, src/main/java/com/soma/snackexercise/dto/mission/response/MissionStartResponse.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- close #120
- 미션테이블에서 startAt 초기화
=> feat : 운동 미션 시작 API 추가 (#120)

src/main/java/com/soma/snackexercise/domain/group/Group.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java
=> [Feature] 일정 시간 간격으로 수행 여부 확인 후 자동 독촉 알림 보내기

src/main/java/com/soma/snackexercise/repository/group/GroupRepository.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java
=> fix : 스케줄러에서 종료되지 않은 그룹들을 조회하도록 변경 (#122)

src/main/java/com/soma/snackexercise/controller/mission/MissionController.java, src/main/java/com/soma/snackexercise/domain/mission/Mission.java, src/main/java/com/soma/snackexercise/dto/mission/request/MissionCancelRequest.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
=> [Feature] 미션 중도 중단 API 추가

src/main/java/com/soma/snackexercise/controller/mission/MissionController.java, src/main/java/com/soma/snackexercise/controller/notification/NotificationController.java, src/main/java/com/soma/snackexercise/domain/notification/NotificationMessage.java, src/main/java/com/soma/snackexercise/dto/notification/request/SendManualReminderRequest.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java, src/main/java/com/soma/snackexercise/service/notification/NotificationService.java
- close #127
- 독촉하기 알림 버튼 클릭시 수동으로 독촉 푸시 알림 전송 API 구현
- 알림 메세지 Enum 수동, 자동 분리
- 독촉 푸시 알림 전송 API 구현
=> [Feature] 독촉하기 버튼 클릭시 수동으로 독촉 푸시 알림 전송 API

src/main/java/com/soma/snackexercise/controller/HealthController.java, src/main/java/com/soma/snackexercise/controller/auth/AuthController.java, src/main/java/com/soma/snackexercise/controller/exercise/ExerciseController.java, src/main/java/com/soma/snackexercise/controller/group/GroupController.java, src/main/java/com/soma/snackexercise/controller/member/MemberController.java, src/main/java/com/soma/snackexercise/controller/mission/MissionController.java, src/main/java/com/soma/snackexercise/controller/signup/SignupController.java, src/main/java/com/soma/snackexercise/repository/member/MemberRepository.java
- close #109
- API url 네이밍 리팩토링
- 각 API url 앞에 붙인 /api를 삭제하였습니다.
=> [Refactor] API url 네이밍 리팩토링

src/main/java/com/soma/snackexercise/domain/notification/NotificationMessage.java, src/main/java/com/soma/snackexercise/repository/group/GroupRepository.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java, src/test/java/com/soma/snackexercise/controller/group/GroupControllerAdviceTest.java, src/test/java/com/soma/snackexercise/controller/group/GroupControllerIntegrationTest.java, src/test/java/com/soma/snackexercise/controller/group/GroupControllerTest.java
- close #133 
- 그룹 종료일자에 비활성화 시키는 스케줄러 추가
- 운동 그룹 컨트롤러 테스트코드 URI 변경
=> [Feature] 그룹 종료일자에 비활성화 시키는 스케줄러 추가

src/main/java/com/soma/snackexercise/service/group/GroupService.java, src/main/java/com/soma/snackexercise/service/mission/MissionUtil.java
- 그룹 시작 시, 현재 시각이 그룹의 운동 시간 범위 내라면 미션 할당
- 그룹 시작 시, 미션 할당이 바로 일어나는 로직이 없었기에, 현재 시각이 그룹의 운동 시간 범위 내라면 미션 할당하는 로직을 추가하였다.
=> [Fix] 그룹 시작 시, 현재 시각이 그룹의 운동 시간 범위 내라면 미션 할당

src/main/java/com/soma/snackexercise/config/SecurityConfig.java, src/main/java/com/soma/snackexercise/controller/mission/MissionController.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- close #141
- 회원 랜덤 운동 API와 비회원 랜덤 운동 API
- 내용을 적어주세요.
=> [Feature] 회원 / 비회원 랜덤 운동 API

src/main/java/com/soma/snackexercise/domain/group/Group.java
- 그룹 수정시, 독촉 검사 시간 간격, 미션 1개당 최대 독촉 검사 횟수 update 로직 추가
- Group Entity의 update함수 수정
=> [Fix] 그룹 수정시, 독촉 검사 시간 간격, 미션 1개당 최대 독촉 검사 횟수 update 로직 추가

src/main/java/com/soma/snackexercise/service/notification/FirebaseCloudMessageService.java
- EC2에 해당 코드를 올릴 시 빈 생성 에러 발생
- 내용을 적어주세요.
=> [Fix] EC2에서 FCM 초기화 못하는 에러 해결을 위한 임시 주석 처리

src/main/java/com/soma/snackexercise/config/FCMConfig.java, src/main/java/com/soma/snackexercise/service/notification/FirebaseCloudMessageService.java
- EC2에서 FCM 초기화시 발생하는 에러를 해결
- FCM Config 작성
=> [Fix] EC2에서 FCM 초기화 못하는 에러 해결

src/main/java/com/soma/snackexercise/config/FCMConfig.java, src/main/java/com/soma/snackexercise/service/notification/FirebaseCloudMessageService.java
- EC2에서 FCM 초기화 못하는 에러 해결을 위해 임시 주석처리
- 내용을 적어주세요.
=> [Fix] EC2에서 FCM 초기화 못하는 에러 해결을 위해 임시 주석처리

src/main/java/com/soma/snackexercise/advice/ErrorCode.java, src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- 아직 프론트와 fcm 토큰 연동 처리를 하지 않아서 에러가 터지는 문제를 방지하기 위해서 임시 주석처리를 진행하였다.
- 내용을 적어주세요.
=> [Fix] FCM 토큰 유무 검증 주석처리

src/main/java/com/soma/snackexercise/domain/mission/Mission.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java, src/test/java/com/soma/snackexercise/factory/dto/GroupUpdateFactory.java, src/test/java/com/soma/snackexercise/factory/entity/GroupFactory.java, src/test/java/com/soma/snackexercise/service/mission/MissionSchedulerServiceUnitTest.java
- close #150 
- 스케줄러 메소드 단위 테스트 작성
=> [Test] 스케줄러 메소드 단위 테스트 작성

.github/workflows/prod-deploy.yml, appspec.yml, docker-compose-prod.yml, scripts/run.sh, scripts/stop.sh, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java, src/main/java/com/soma/snackexercise/service/mission/MissionUtil.java
- close #153
- github actions를 사용한 prod-deploy
- code deploy를 위한 script 파일, appspec.yml 파일 작성
- prod github actions workflow 수정
- prod 용 docker-compose 파일 생성
- MissionUtil, MissionSchecdulerService 로그 출력시 회원 name이 아닌, nickname 출력으로 수정
=> [Feature] github actions를 사용한 prod-deploy

.gitignore, build.gradle, src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java, src/main/resources/application-local.yml, src/main/resources/application.yml
- close #163
- 에러 발생시 로그 기반 추적을 위한 Sentry APM 툴 도입
- Sentry 의존성 및 에러 캐치 코드 추가
=> [Feat] Sentry 도입

src/main/java/com/soma/snackexercise/controller/mission/MissionController.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- 미션 시작하기 API queryparam으로 랜덤 여부 구분하려 로직 분기 처리
- 내용을 적어주세요.
=> [Fix] 미션 시작하기 API queryparam으로 랜덤 여부 구분하려 로직 분기 처리

.github/workflows/prod-deploy.yml, build.gradle, docker-compose-prod.yml, scripts/deploy.sh, scripts/switch.sh, src/main/java/com/soma/snackexercise/config/SecurityConfig.java, src/main/java/com/soma/snackexercise/controller/HealthController.java, src/main/resources/application.yml
- docker 컨테이너를 사용하여 blue, green 무중단 배포 전략을 구현하였습니다.
- 현재 실행중인 환경 profile 확인 후 새로운 컨테이너 실행하는 로직(deploy.sh)과 nginx가 바라포는 포트를 변경하는 스크립트(switch.sh) 작성
- prod-env profile을 prod-blue-env, prod-green-env로 분리
=> [Feat] prod 환경 blue, green 배포

.github/workflows/prod-deploy.yml
=> [Fix] prod-deploy.yml

src/main/java/com/soma/snackexercise/service/group/GroupService.java
- 운동 그룹 시작시 알림 메세지 enum이 잘못 설정 되어있는 것을 수정하였습니다.
- 내용을 적어주세요.
=> [Fix] 운동 시작시 알림 메세지 수정

.github/workflows/prod-deploy.yml, build.gradle, scripts/deploy.sh, scripts/switch.sh, src/main/java/com/soma/snackexercise/config/FCMConfig.java, src/main/java/com/soma/snackexercise/service/group/GroupService.java
=> [Fix] blue, green 배포 쉘 스크립트 수정

src/main/java/com/soma/snackexercise/domain/mission/Mission.java
- 그룹 시작후 바로 자동독촉 오는 에러 해결
- 내용을 적어주세요.
=> [Fix] 그룹 시작후 바로 자동독촉 오는 에러 해결

.github/workflows/prod-deploy.yml, build.gradle, scripts/deploy.sh, scripts/switch.sh, src/main/java/com/soma/snackexercise/advice/ErrorCode.java, src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java, src/main/java/com/soma/snackexercise/controller/HealthController.java, src/main/java/com/soma/snackexercise/controller/auth/MvpAuthController.java, src/main/java/com/soma/snackexercise/domain/mission/Mission.java, src/main/java/com/soma/snackexercise/domain/notification/NotificationMessage.java, src/main/java/com/soma/snackexercise/dto/auth/MvpLoginRequest.java, src/main/java/com/soma/snackexercise/service/group/GroupService.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- 로그인, 회원가입 시 FCM 토큰 Blank validation 추가
- 알림메세지에 그룹명, 회원명 추가
- validation 의존성 추가
- 그룹 시작 후 바로 자동 독촉 메세지오는 에러 해결
- profile 확인 API url 수정
- 내용을 적어주세요.
=> [Fix] FCM 토큰 빈값 검증 로직 추가, prod cicd profile확인 API url 수정

scripts/deploy.sh
=> [Fix] deploy.sh

src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java
- close #184
- 그룹 시작시간에 미션 할당 알림을 각 그룹마다 미션 수행자에 대해서만 알림 전송되도록 수정
- tokenList 변수 삭제 및 그룹 for문을 돌면서 각 그룹의 미션 수행자에 대해서만 알림 전송되도록 수정
=> [Fix] 그룹 시작시간에 미션 할당 알림을 각 그룹마다 미션 수행자에 대해서만 알림 전송되도록 수정

src/main/java/com/soma/snackexercise/controller/mission/MissionMvpController.java, src/main/java/com/soma/snackexercise/domain/exercise/Exercise.java, src/main/java/com/soma/snackexercise/domain/mission/Mission.java, src/main/java/com/soma/snackexercise/dto/mission/request/MissionMvpStartRequest.java, src/main/java/com/soma/snackexercise/service/mission/MissionMvpService.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java, src/main/java/com/soma/snackexercise/util/constant/Difficulty.java
- close #186 
- 미션 부여뒤, easy / hard 운동 난이도 선택 후, 미션 시작할 수 있도록 추가
=> feat : 1차 mvp A/B 테스트용 미션 부여 API 추가 (#186)

src/main/java/com/soma/snackexercise/domain/exercise/Exercise.java
=> fix : 운동 엔티티 난이도 필드 EnumType String으로 변경 (#186)

src/main/java/com/soma/snackexercise/domain/mission/Mission.java, src/main/java/com/soma/snackexercise/service/mission/MissionService.java
- close #190
- 운동 수행 시간 단위를 minute에서 second로 수정
- 내용을 적어주세요.
=> [Fix] 미션 수행완료 시간 기록 오류

src/main/java/com/soma/snackexercise/domain/BaseTimeEntity.java, src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java
=> fix : 미션 시작 스케줄러 기존 미션 수행자 새로 미션 할당되는 문제 수정 (#193)
